### ISSUE TITLE
Detail sidebar issues

### ISSUE THREAD

**Issue by Janaka-Steph** [sapio-lang/sapio-studio#6]
It would improve Tux usability to be able to resize the sidebar, being able to scroll it independently of the canvas and being able to read the totality of the values (address, script, transaction hex).

**Comment by JeremyRubin** [comment]
totally. It would also be cool (I have no idea how to do it) if the sidebar could be a pop out like the developer tools.

**Comment by Janaka-Steph** [comment]
Ha yes, having the details in a standalone window would be practical.

**Comment by JeremyRubin** [comment]
partly fixed; sidebar now scrolls independently. I also made it more compact.

Will think about the pop-out or drag functionality longer term.

**Comment by JeremyRubin** [comment]
now resizable too :)
